# Generated by Django 2.0.6 on 2021-08-21 04:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='producto',
            fields=[
                ('pk_producto', models.AutoField(primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=9)),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=2)),
            ],
        ),
        migrations.CreateModel(
            name='sell',
            fields=[
                ('pk_sell', models.AutoField(primary_key=True, serialize=False)),
                ('name_client', models.CharField(default='n/a', max_length=80)),
                ('date_buy', models.DateField(auto_now_add=True)),
                ('amount', models.IntegerField()),
                ('fk_producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webperros.producto')),
            ],
        ),
    ]
