# Generated by Django 2.0.6 on 2021-08-21 04:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webperros', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='stock',
            fields=[
                ('ps_stock', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.IntegerField()),
                ('fk_producto', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='webperros.producto')),
            ],
        ),
    ]
