# Generated by Django 2.0.6 on 2021-08-26 04:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webperros', '0002_stock'),
    ]

    operations = [
        migrations.CreateModel(
            name='categorias',
            fields=[
                ('pk_categorias', models.AutoField(primary_key=True, serialize=False)),
                ('variedad', models.CharField(max_length=80)),
                ('editorial', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='libro',
            fields=[
                ('pk_libro', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('autor', models.CharField(max_length=50)),
                ('paginas', models.TextField()),
                ('fecha_de_lanzamiento', models.DateField()),
                ('idioma', models.CharField(max_length=50)),
                ('disponibilidad', models.CharField(max_length=50)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=2)),
            ],
        ),
        migrations.RemoveField(
            model_name='sell',
            name='fk_producto',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='fk_producto',
        ),
        migrations.DeleteModel(
            name='producto',
        ),
        migrations.DeleteModel(
            name='sell',
        ),
        migrations.DeleteModel(
            name='stock',
        ),
        migrations.AddField(
            model_name='categorias',
            name='fk_libro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webperros.libro'),
        ),
    ]
