# Generated by Django 2.0.6 on 2021-08-26 04:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webperros', '0003_auto_20210825_2211'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categorias',
            name='fk_libro',
        ),
        migrations.DeleteModel(
            name='categorias',
        ),
        migrations.DeleteModel(
            name='libro',
        ),
    ]
