# Generated by Django 2.0.6 on 2021-09-05 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webperros', '0005_auto_20210825_2214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libro',
            name='precio',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
